Update to sphinx 7.3.7 and pytest 8.2.2 (#42)
Fix issues with requirements-dev.txt, pytest and sphinx.

  * Remove lxml as it fails to build with error `fatal error C1083:
    Cannot open include file: 'libxml/xpath.h': No such file or
    directory`. Use built-in xml in calibration_example.py instead.
  * Remove black, pylint and rope as they are formatting/lint tools that
    are not used anywhere in the repository.
    https://github.com/astral-sh/ruff is all the rage these days anyway.
  * Remove wheel as with Python 3.12 packaging it is setup automatically.
  * Upgrade to twine 5.1.0.

Upgrade pytest to 8.2.2 to fix deprecation warning:

```
DeprecationWarning: ast.Str is deprecated and will be removed in Python
3.14; use ast.Constant instead
```

Fix deprecation warning caused by upgrade in several places:

```
PytestDeprecationWarning: test_connect_no_loop
is asynchronous and explicitly requests the "event_loop" fixture.
Asynchronous fixtures and test functions should use
"asyncio.get_running_loop()" instead
```

  * Upgrade sphinx to 7.3.7.
  * Remove usage of `sphinxcontrib-asyncio` and rely on sphinx default
    handling of `async` functions (`autocofunction` changed to
    `autofunction`).
  * Remove "coroutine" terminology as in Python it is more commonly
    refered to as async functions.
  * Newer sphinx requires language to be set so set it to `'en'`.
  * Fix warning `html_static_path entry '_static' does not exist` by
    removing it from config.py.
  * Fix `ERROR: Unknown target name: "qtm_rt.connect".` by removing
    redundant underscore.

Co-authored-by: Daniel Oom <daniel.oom@qualisys.se>